# -*- coding: utf-8 -*-
"""435project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16CPQUZQxisXzZ8A24g-YPYzT4M7pkFXq

***Import Libraries***
"""

import pandas as pd
import geopandas as gpd
import numpy as np
from shapely.geometry import Polygon
from scipy.spatial.distance import cosine
from scipy.optimize import linear_sum_assignment
import glob
import os
from shapely import wkt
import zipfile
import matplotlib.pyplot as plt
import seaborn as sns

"""***Data Preprocessing***

Combine geometric data with stats, and ideal plans files. Compute the centroid and save in a separate file.
"""

maps = pd.read_csv("/content/IL_2020_maps.csv")
print(maps.head())
print(maps.size)
maps.columns

#Path to 100 ideal plans zip file
path_to_zip_file = '/content/idealPlans.zip'
extract_to_folder = 'ideal_content'

with zipfile.ZipFile(path_to_zip_file, 'r') as zip_ref:
    zip_ref.extractall(extract_to_folder)


search_path = os.path.join(extract_to_folder, "**", "*.csv")
all_files = glob.glob(search_path, recursive=True)

li = []

for filename in all_files:
    # Read the CSV
    df = pd.read_csv(filename, index_col=None, header=0)

    # Extract the base filename (e.g., 'idealPlan_37.csv')
    base_name = os.path.basename(filename)

    # Remove extension (e.g., 'idealPlan_37')
    name_no_ext = os.path.splitext(base_name)[0]

    # Logic to get '37' from 'idealPlan_37'
    try:
        # Splits at underscore and takes the last part
        plan_value = name_no_ext.split('_')[-1]
    except IndexError:
        plan_value = 'Unknown'

    # Assign to new column
    df['Plan'] = plan_value

    li.append(df)

# Check if we actually found files before trying to merge
if len(li) > 0:
    merged_ideal = pd.concat(li, axis=0, ignore_index=True)
    merged_ideal.to_csv('merged_ideal_plans.csv', index=False)
    print(f"Success! Merged {len(li)} files into 'merged_all_plans.csv'")
    print(merged_ideal.head())
else:
    print("No CSV files were found in the zipped folder.")

# Convert maps dataframe to GeoDataFrame for centroid computation
maps['geometry'] = maps['geometry_wkt'].apply(wkt.loads)
maps_gdf = gpd.GeoDataFrame(maps, geometry='geometry')

# Dissolve precincts to districts (assuming districts 1-17)
districts = maps_gdf.dissolve(
    by='cd_2020',
    aggfunc={
        'pop': 'sum',
        'area_land': 'sum',
        'area_water': 'sum'
    }
).reset_index()

# Calculate geographic features (centroids, area, and perimeter)
districts['centroid_x'] = districts.geometry.centroid.x
districts['centroid_y'] = districts.geometry.centroid.y
districts['geom_area'] = districts.geometry.area
districts['perimeter'] = districts.geometry.length

print(f"\nDistricts computed: {len(districts)} districts")

stats = pd.read_csv('/content/ideal_stats.csv')
stats.head()
print(stats.columns)

#join stats + ideal set files because stats has draw, and ideal set has top 100 plan numbers

# Standardize the key columns to Strings to ensure they match
merged_ideal['Plan'] = merged_ideal['Plan'].astype(str)
stats['draw'] = stats['draw'].astype(str)

# Perform the Merge
# left_on='Plan': Use 'Plan' column from df_ideal
# right_on='Draw': Use 'Draw' column from df_stats
# how='left': Keep all rows from df_ideal (the "merged ideal" file)
ideal_stats = pd.merge(
    merged_ideal,
    stats,
    left_on='Plan',
    right_on='draw',
    how='left'
)

# Save the result
ideal_stats.to_csv('final_combined_data.csv', index=False)

print("Merge complete.")
print(ideal_stats.head())
ideal_stats.drop([ 'total_vap', 'plan_dev',
       'pop_hisp', 'pop_white', 'pop_black', 'pop_aian', 'pop_asian',
       'pop_nhpi', 'pop_other', 'pop_two', 'vap_hisp', 'vap_white',
       'vap_black', 'vap_aian', 'vap_asian', 'vap_nhpi', 'vap_other',
       'vap_two', 'pre_16_dem_cli', 'pre_16_rep_tru', 'uss_16_dem_duc',
       'uss_16_rep_kir', 'gov_18_dem_pri', 'gov_18_rep_rau', 'atg_18_dem_rao',
       'atg_18_rep_har', 'sos_18_dem_whi', 'sos_18_rep_hel', 'pre_20_dem_bid',
       'pre_20_rep_tru', 'uss_20_dem_dur', 'uss_20_rep_cur', 'arv_16',
       'adv_16', 'arv_18', 'adv_18', 'arv_20', 'adv_20',
       'muni_splits', 'ndv', 'nrv', 'ndshare', 'e_dvs', 'pr_dem', 'e_dem'], inplace=True, axis=1)
print(ideal_stats.columns)

# Cross join: combine every draw with every district
# This creates all combinations of draw numbers and district numbers
ideal_stats['key'] = 1
districts['key'] = 1
final = ideal_stats.merge(districts, on='key', how='outer').drop('key', axis=1)

print(f"\nFinal dataset: {len(final)} rows")
print(f"This represents {ideal_stats['Plan'].nunique()} draws × {len(districts)} districts")
print(f"Columns: {list(final.columns)}")

# Save the results
final.to_csv('ideal_stats_maps.csv', index=False)
print("\nSaved to ideal_stats_maps.csv")

final.head()

"""***Compute Necessary Functions***"""

def calculate_overlap(geom1, geom2):
    """Calculate Jaccard similarity (intersection/union) of two geometries"""
    try:
        # Convert to Polygon if needed
        if isinstance(geom1, list):
            geom1 = Polygon(geom1[0][0])
        if isinstance(geom2, list):
            geom2 = Polygon(geom2[0][0])

        intersection_area = geom1.intersection(geom2).area
        union_area = geom1.union(geom2).area

        if union_area > 0:
            return intersection_area / union_area
        else:
            return 0
    except:
        return 0

def build_cost_matrix(plan1, plan2):
    """
    Build a cost matrix to match districts between two plans.
    Lower cost = better match
    """
    n1 = len(plan1)
    n2 = len(plan2)

    cost_matrix = np.zeros((n1, n2))

    # For each pair of districts, calculate the cost
    for i in range(n1):
        for j in range(n2):
            # Get geometries
            geom1 = plan1.iloc[i].geometry
            geom2 = plan2.iloc[j].geometry

            # Calculate overlap (higher overlap is better, so cost = 1 - overlap)
            overlap = calculate_overlap(geom1, geom2)
            overlap_cost = 1 - overlap

            # Calculate centroid distance
            x1 = plan1.iloc[i]['centroid_x']
            y1 = plan1.iloc[i]['centroid_y']
            x2 = plan2.iloc[j]['centroid_x']
            y2 = plan2.iloc[j]['centroid_y']

            distance = np.sqrt((x1 - x2)**2 + (y1 - y2)**2)

            # Normalize distance (assume max distance is sqrt of state area)
            max_distance = 500000  # rough estimate, adjust as needed
            normalized_distance = min(distance / max_distance, 1.0)

            # Calculate area difference
            if 'area_m2' in plan1.columns:
                area1 = plan1.iloc[i]['area_m2']
                area2 = plan2.iloc[j]['area_m2']
            else:
                area1 = plan1.iloc[i]['geo_area']
                area2 = plan2.iloc[j]['geo_area']

            area_diff = abs(area1 - area2) / max(area1, area2)

            # Combine costs (weighted sum)
            # Overlap is most important (70%), then distance (20%), then area (10%)
            cost_matrix[i, j] = 0.7 * overlap_cost + 0.2 * normalized_distance + 0.1 * area_diff

    return cost_matrix

# Find which compactness metrics are complete (no missing values)
def get_complete_metrics(plan_data):
    """Get list of compactness columns that have no NaN values"""
    comp_columns = [col for col in plan_data.columns if col.startswith('comp_')]

    complete = []
    for col in comp_columns:
        if plan_data[col].notna().all():
            complete.append(col)

    return complete

# Match districts between two plans
def match_districts(plan1, plan2):
    """Use Hungarian algorithm to match districts"""

    # Build cost matrix
    costs = build_cost_matrix(plan1, plan2)

    # Solve the assignment problem
    row_indices, col_indices = linear_sum_assignment(costs)

    # Return as dictionary
    matching = {}
    for i, j in zip(row_indices, col_indices):
        matching[i] = j

    return matching

# Create a vector from compactness metrics
def make_vector(plan_data, metric_columns, order=None):
    """Flatten compactness metrics into a single vector"""
    # Reorder if needed
    if order is not None:
        data = plan_data.iloc[order]
    else:
        data = plan_data.sort_values('district_x')

    # Get just the metric columns and flatten
    vector = data[metric_columns].values.flatten()

    return vector

def calculate_similarity(plan1_data, plan2_data, plan1_name, plan2_name):
    """Calculate how similar two plans are based on compactness metrics"""

    # Match districts first
    matching = match_districts(plan1_data, plan2_data)

    # Find metrics that both plans have complete data for
    metrics1 = get_complete_metrics(plan1_data)
    metrics2 = get_complete_metrics(plan2_data)
    common_metrics = [m for m in metrics1 if m in metrics2]

    if len(common_metrics) == 0:
        print("  Error: No common metrics!")
        return None

    print(f"  Using {len(common_metrics)} metrics: {common_metrics}")

    # Make vectors
    vector1 = make_vector(plan1_data, common_metrics)

    # Reorder plan2 to match plan1
    plan2_order = [matching[i] for i in range(len(matching))]
    vector2 = make_vector(plan2_data, common_metrics, order=plan2_order)

    # Calculate cosine similarity
    # scipy.cosine gives distance, so similarity = 1 - distance
    similarity = 1 - cosine(vector1, vector2)

    print(f"Similarity: {similarity:.4f}")

    return similarity

"""Main Program: Compare User Plan to each plan in Ideal Set. Rank the output.

"""

user_plans = ['/content/example2_compactness.csv','/content/example2_compactness.csv','/content/example3_compactness.csv', '/content/example4_compactness.csv', '/content/example5_compactness.csv']

for i, plan_file in enumerate(user_plans):
  print(f"\n--- Processing User Plan {i+1} from {plan_file} ---")
  user_plan = pd.read_csv(plan_file)

  # Convert geometry WKT to shapely geometry objects and create GeoDataFrames
  user_plan['geometry'] = user_plan['geometry_wkt'].apply(wkt.loads)
  user_plan_gdf = gpd.GeoDataFrame(user_plan, geometry='geometry')

  # Calculate geographic features for user_plan_gdf: centroids and area
  user_plan_gdf['centroid_x'] = user_plan_gdf.geometry.centroid.x
  user_plan_gdf['centroid_y'] = user_plan_gdf.geometry.centroid.y
  user_plan_gdf['geo_area'] = user_plan_gdf.geometry.area # Calculate area from geometry directly

  # Rename 'district' in user_plan_gdf to 'district_x' to match 'make_vector' function's expectation
  user_plan_gdf.rename(columns={'district': 'district_x'}, inplace=True)

  print("User-Drawn Plan (first 5 rows):")
  display(user_plan_gdf.head())

  # Ensure 'Plan' and 'draw' are string types for consistent merging
  merged_ideal['Plan'] = merged_ideal['Plan'].astype(str)
  stats['draw'] = stats['draw'].astype(str)

  # Correctly merge merged_ideal and stats on 'Plan'/'draw' AND 'district'
  # This creates an intermediate DataFrame where each row correctly corresponds to a unique
  # district within a specific plan, preventing the cross-product issue.
  intermediate_ideal_stats = pd.merge(
      merged_ideal, # Has 'district' and 'Plan'
      stats,        # Has 'district' and 'draw'
      left_on=['Plan', 'district'],
      right_on=['draw', 'district'],
      how='left',
      suffixes=('_merged_ideal', '_stats')
  )

  # The resulting dataframe 'intermediate_ideal_stats' will have a 'district' column (the common one).
  # Rename 'district' to 'district_x' to match 'make_vector' function's expectation.
  intermediate_ideal_stats.rename(columns={'district': 'district_x'}, inplace=True)
  # Rename the plan identifier column from stats to 'draw'
  intermediate_ideal_stats.rename(columns={'draw_stats': 'draw'}, inplace=True)

  # Now merge this correctly structured intermediate_ideal_stats with the geographic data (districts)
  final_ideal_plans_gdf = intermediate_ideal_stats.merge(districts,
                                                left_on='district_x', # Merge on the now consistent 'district_x'
                                                right_on='cd_2020',
                                                how='inner',
                                                suffixes=('_ideal_metrics', '_map_geom'))

  # Convert to GeoDataFrame after merge to enable geographic operations
  final_ideal_plans_gdf = gpd.GeoDataFrame(final_ideal_plans_gdf, geometry='geometry')

  # Ensure geometric features are calculated for the ideal plans
  final_ideal_plans_gdf['centroid_x'] = final_ideal_plans_gdf.geometry.centroid.x
  final_ideal_plans_gdf['centroid_y'] = final_ideal_plans_gdf.geometry.centroid.y
  final_ideal_plans_gdf['geo_area'] = final_ideal_plans_gdf.geometry.area

  print("\nCalculating similarity for each ideal plan...")

  similarity_results = []
  # Filter out NaN values from 'draw' column before getting unique draws
  unique_draws = final_ideal_plans_gdf['draw'].dropna().unique()

  for draw_id in unique_draws:
      # Extract data for a single ideal plan (should now have 17 rows)
      single_ideal_plan_gdf = final_ideal_plans_gdf[final_ideal_plans_gdf['draw'] == draw_id].copy()

      print(f"\nComparing with Ideal Plan (Draw: {draw_id})")
      similarity_score = calculate_similarity(single_ideal_plan_gdf, user_plan_gdf, f"Ideal Plan {draw_id}", "User-Drawn Plan")

      if similarity_score is not None:
          similarity_results.append({'draw': draw_id, 'similarity': similarity_score})

  # Rank the results
  if similarity_results:
      ranked_results = pd.DataFrame(similarity_results).sort_values(by='similarity', ascending=False)
      print(f"\n--- Ranked Ideal Plans by Similarity to User-Drawn Plan ({plan_file}) ---")
      print(ranked_results.head())

      # Plotting the distribution of similarity scores
      plt.figure(figsize=(10, 6))
      sns.histplot(ranked_results['similarity'], kde=True, bins=10)
      plt.title(f'Distribution of Similarity Scores for Ideal Plans vs User Plan {i+1}')
      plt.xlabel('Cosine Similarity Score')
      plt.ylabel('Number of Ideal Plans')
      plt.grid(axis='y', alpha=0.75)
      plt.show()
  else:
      print("No similarity results to display.")