# -*- coding: utf-8 -*-
"""vector_cosine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgQF-N8kg3GMm-NaTu8T7k45KijUkd8q

Import Packages
"""

import matplotlib.pyplot as plt #plotting
import matplotlib.image as mpimg #plot images
from PIL import Image #process images
import numpy as np #process vector arrays
from sklearn.metrics.pairwise import cosine_similarity #compute cosine similarity

"""Open and Read File with Vector Arrays"""

# Create a dummy file with vector arrays for demonstration
#These arrays would include the compactness metrics for each district in every ideal plan.
with open('vectors.txt', 'w') as f:
    f.write('5.0 7.0 56.0 3.0\n')
    f.write('1.1 2.1 3.1 4.1\n')
    f.write('5.0 6.0 7.0 8.0\n')
    f.write('1.0 2.0 3.0 4.0\n')

"""Pass Vector for Newly Drawn Plan"""

# Define the input (plan) vector x
input_vector_x = np.array([1.0, 2.0, 3.0, 4.0])
print(f"Input vector x: {input_vector_x}")

"""Define Function to Compute Vector Cosine Similarity"""

#Function to compute cosine similarity
def calculate_similarity(vector1, vector2):
    # Flatten the 2D image arrays into 1D vectors
    flat_vector1 = vector1.flatten().reshape(1, -1)
    flat_vector2 = vector2.flatten().reshape(1, -1)
    # Calculate cosine similarity
    similarity = cosine_similarity(flat_vector1, flat_vector2)
    return similarity

"""Compute VectorCosineSim For All Ideal Plans"""

# Read vectors from the file and compute cosine similarity
read_vectors = []
with open('vectors.txt', 'r') as f:
    for line in f:
        # Convert each line to a NumPy array of floats
        vector = np.array(list(map(float, line.strip().split())))
        read_vectors.append(vector)

print(f"Loaded {len(read_vectors)} vectors from 'vectors.txt'.")

# List to store all similarity values
all_similarities = []

# Compute and print similarities
print("\nCosine Similarities with input_vector_x:")
for i, vec in enumerate(read_vectors):
    similarity = calculate_similarity(vec, input_vector_x)
    print(f"Vector {i+1}: {vec} | Similarity: {similarity.item():.4f}")
    all_similarities.append(similarity.item()) # Store the scalar similarity

"""Compute Average Cosine Similarity"""

# Calculate the average of all collected similarities
if all_similarities:
    average_similarity = sum(all_similarities) / len(all_similarities)
    print(f"Average Cosine Similarity: {average_similarity:.4f}")
else:
    print("No similarities were calculated.")